// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIzdQQif7mqt9L7Tnstgd0b5g_8Z1iMlA',
    appId: '1:536720564203:web:18e096f6d339cf283443ae',
    messagingSenderId: '536720564203',
    projectId: 'jopfinder-c3ac2',
    authDomain: 'jopfinder-c3ac2.firebaseapp.com',
    storageBucket: 'jopfinder-c3ac2.appspot.com',
    measurementId: 'G-08FBMLTYHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS0Lm7G6ZPBKrHLD4afArW6MVJjdDTcbU',
    appId: '1:536720564203:android:c681596a5cb87f8f3443ae',
    messagingSenderId: '536720564203',
    projectId: 'jopfinder-c3ac2',
    storageBucket: 'jopfinder-c3ac2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWmFrznvBBijOUUolYvViQ_p92_lzJiww',
    appId: '1:536720564203:ios:04bb34abfbfd13053443ae',
    messagingSenderId: '536720564203',
    projectId: 'jopfinder-c3ac2',
    storageBucket: 'jopfinder-c3ac2.appspot.com',
    iosClientId: '536720564203-rl68kcorur0v17ugdspnmf6c1hbrrd3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsqueJobfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWmFrznvBBijOUUolYvViQ_p92_lzJiww',
    appId: '1:536720564203:ios:2c9cad4cc24caaad3443ae',
    messagingSenderId: '536720564203',
    projectId: 'jopfinder-c3ac2',
    storageBucket: 'jopfinder-c3ac2.appspot.com',
    iosClientId: '536720564203-qki3i732ei0n4rdf41tebhpcel8didi0.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsqueJobfinder.RunnerTests',
  );
}
