// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdXxD1hxCl7y8xUtRuJON8ozpwwdqv7D0',
    appId: '1:829323422004:web:18890262d1f30c94f59d61',
    messagingSenderId: '829323422004',
    projectId: 'jobsque-fc5cc',
    authDomain: 'jobsque-fc5cc.firebaseapp.com',
    storageBucket: 'jobsque-fc5cc.appspot.com',
    measurementId: 'G-2S2E5N8JW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdBPkZQvXJYAXMLroCigxfpasmIYvYOBk',
    appId: '1:829323422004:android:b5aac8cc3d8483dff59d61',
    messagingSenderId: '829323422004',
    projectId: 'jobsque-fc5cc',
    storageBucket: 'jobsque-fc5cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB01zCx2ixR-8p2igO5NaqRuougiij8Q54',
    appId: '1:829323422004:ios:0bd4d68c2727b2e2f59d61',
    messagingSenderId: '829323422004',
    projectId: 'jobsque-fc5cc',
    storageBucket: 'jobsque-fc5cc.appspot.com',
    iosClientId: '829323422004-drkb4047lllgt0f5s9vgp3pcgne9vn2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsqueJobfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB01zCx2ixR-8p2igO5NaqRuougiij8Q54',
    appId: '1:829323422004:ios:93f21f9b4ae3a771f59d61',
    messagingSenderId: '829323422004',
    projectId: 'jobsque-fc5cc',
    storageBucket: 'jobsque-fc5cc.appspot.com',
    iosClientId: '829323422004-goo5dl068deplhi1gon1vd6rs8dsfn21.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsqueJobfinder.RunnerTests',
  );
}
